### ISSUE TITLE
test harness hangs in Travis

### ISSUE THREAD

**Issue by pmqs** [LLFourn/p6-CompUnit-Util#2]
I make use of this module in [Archive-SimpleZip](https://github.com/pmqs/Archive-SimpleZip). The Travis build for it was timing out in this module.

Cloned **CompUnit::Util** and triggered a Travis build to see where the problem is

> $ perl6 --version
> This is Rakudo version 2017.04.3-50-gd057efd built on MoarVM version 2017.04-44-gf0db882
> implementing Perl 6.c.
> $ prove -v -e 'perl6 -Ilib' t/
> t/01-utils.t ............... 
> 1..17
> ok 1 - load
> ok 2 - load again returns same thing
> ok 3 - found Test
> ok 4 - found CompUnit::Util
> ok 5 - find-loaded on non-existent module returns false
> ok 6 - returns Failure
> 
> 
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
> 
> The build has been terminated

Looks like this is the line from **t/01-utils.t** is causing the problem

> ok all-loaded()».short-name.pick(*) ~~ set('CompUnit::Util','NativeCall','Test'),

**Comment by LLFourn** [comment]
Thanks. I guess this module has bitrotted quite a lot as the rakudo internals have changed quite a bit.

I'll take a look at this tomorrow. It's probably worth gettiing rid of all-loaded anyways since you can just do:
```perl6
 $*REPO.repo-chain.map(*.loaded).flat
```
or something similar now.

**Comment by LLFourn** [comment]
Fixed ;)
