### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by pmqs** [LLFourn/p6-CompUnit-Util#4]
Think something may have changed in perl6

> t/02-re-export.t ........... ===SORRY!===
> Cannot invoke this object (REPR: Null; VMNull)
> Dubious, test returned 1 (wstat 256, 0x100)
> No subtests run 
> 
> t/05-rexport-everything.t .. ===SORRY!===
> Cannot invoke this object (REPR: Null; VMNull)
> Dubious, test returned 1 (wstat 256, 0x100)
> No subtests run 
>

**Comment by LLFourn** [comment]
Yep. That ain't good. Thanks for reporting.

**Comment by LLFourn** [comment]
Should be fixed. I just uncommented the bit of the test file that was causing it submitted a rakudobug. https://rt.perl.org/Public/Bug/Display.html?id=131584
