### ISSUE TITLE
Failure in t/01-utils.t

### ISSUE THREAD

**Issue by tbrowder** [LLFourn/p6-CompUnit-Util#9]
Using Debian and Raku 2024.07.

**Comment by tbrowder** [comment]
I have fixed the error by changing the set symbol. The original unicode symbol was for proper subset [ASCII: (<)] which is incorrect as pointed out by @lizmat. A proper subset MUST have fewer members than the set being compared with.

I changed to the plain subset symbol [ASCII: (<=)] and the test now passes.

Note that @lizmat has removed this module from the Raku ecosystem and it will have to be moved to the Zef/Fez system if you want any updates to be known to users.

If you wish, you can respond to @lizmat's msg to you and the community will adopt this module.

I will prepare a PR to the module regardless.

**Comment by LLFourn** [comment]
Thanks @tbrowder. I won't be maintaining this module anymore so best to fork before fixing.
